package:
  name: um_packing
  version: '{{ environ["VERSION"] }}'

source:
  svn_url: https://code.metoffice.gov.uk/svn/um/mule/trunk
  svn_rev: {{ environ["REVISION"] }} # 126922
  svn_username: {{ environ["SVN_USERNAME"] }}
  svn_password: {{ environ["SVN_PASSWORD"] }}

build:
  number: 0
  skip: true # [not linux-64]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - numpy <2 # [py<313]
    - numpy >=2 # [py>=313]
    - pip
    - shumlib
    - setuptools
  run:
    - python
    - six
    - shumlib

test:
  source_files:
    - um_packing/lib/um_packing/tests
  requires:
    - pytest
  commands:
    - {{ PYTHON }} -m pytest -vv

about:
  home: https://code.metoffice.gov.uk/trac/um/wiki/working_practices_mule
  license: BSD
  license_file: um_packing/LICENCE.txt
  summary: Python extension from the SHUMlib packing library