{% set name = "ug-ants" %}
# {% set version = os.environ.get('VERSION') %}
{% set version = '0.2.0' %}

package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  svn_url: https://code.metoffice.gov.uk/svn/ancil/ug-ants/tags/{{ version }}
  # svn_rev: {{ environ["REVISION"] }} #18115
  svn_rev: 18115
  svn_username: {{ environ["SVN_USERNAME"] }}
  svn_password: {{ environ["SVN_PASSWORD"] }}

build:
  number: 0
  skip: true # [not linux64]

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - numpy<2
    # - cartopy
    # - dask
    # - esmpy
    # - f90nml
    # - gdal
    # - numba
    # - pykdtree
    # - python-stratify
    # - shumlib
    - scitools-iris
    # - um-spiral-search

test:
  imports:
    - ugants
  commands:
    - ug-ants-version
    - $PYTHON -m unittest discover -vs ${SP_DIR}/ug-ants/tests

about:
  home: https://code.metoffice.gov.uk/doc/ancil/ug-ants/latest/contributing.html
  license: BSD
  license_family: BSD
  summary: UG-ANTS is a Python library to provide the capabilities to developing ancillary files on unstructured grids.