{% set name = "mule" %}
{% set version = '1.0' %}
{% set revision = '126922' %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  svn_url: https://code.metoffice.gov.uk/svn/um/mule/trunk
  svn_rev: {{ revision }}
  svn_username: {{ environ["SVN_USERNAME"] }}
  svn_password: {{ environ["SVN_PASSWORD"] }}

build:
  number: 0 # [linux-64]
  number: 1 # [not linux-64]

requirements:
  build:
    - {{ compiler('c') }} # [linux-64]
  host:
    - python
    - pip
    - numpy
    - shumlib # [linux-64]
    - setuptools

outputs:
  - name: um-spiral-search
    script: build_um_spiral_search.sh
    build:
      skip: true # [not linux-64]
    requirements:
      build:
        - {{ compiler('c') }} # [linux-64]
      host:
        - python
        - pip
        - numpy
        - shumlib # [linux-64]
        - setuptools
      run:
        - python
        - numpy
        - shumlib
    test:
      imports:
        - um_spiral_search
      commands:
        - $PYTHON -m unittest discover -vs ${SP_DIR}/um_spiral_search/tests
    about:
      summary: Python extension from the SHUMlib spiral search library.

  - name: um-packing
    script: build_um_packing.sh
    build:
      skip: true # [not linux-64]
    requirements:
      build:
        - {{ compiler('c') }} # [linux-64]
      host:
        - python
        - pip
        - numpy
        - shumlib # [linux-64]
        - setuptools
      run:
        - python
        - numpy
        - shumlib
    test:
      requires:
        - six
      imports:
        - um_packing
      commands:
        - $PYTHON -m unittest discover -vs ${SP_DIR}/um_packing/tests

about:
  home: https://github.com/metomi/mule
  license: BSD
  license_family: BSD
  summary: Mule is a Python API for accessing the various file types used by the UM; the UK Met Office's Unified Model.