{% set name = "ants" %}
{% set version = os.environ.get('VERSION') %}

package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  svn_url: https://code.metoffice.gov.uk/svn/ancil/ants/tags/{{ version }}
  svn_rev: {{ environ["REVISION"] }}
  svn_username: {{ environ["SVN_USERNAME"] }}
  svn_password: {{ environ["SVN_PASSWORD"] }}
  patches:
    - unit_testing.patch

build:
  number: 0
  skip: true # [not linux64]

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - numpy<2
    - cartopy
    - dask
    - esmpy
    - f90nml
    - gdal
    - mule-base
    - numba
    - pykdtree
    - python-stratify
    - scitools-iris
    - um-spiral-search

test:
  requires:
    - mule-utils
    - pytest
  imports:
    - ants
  commands:
    - ancil_2anc.py -h
    - ancil_create_shapefile.py -h
    - ancil_fill_n_merge.py -h
    - ancil_general_regrid.py -h
    - ants-version
    # Perform unit tests with the included patch, to avoid failures due to test syntax problems
    # for different versions.
    # Skipping the integration tests as they require a specific environment setup.
    - test_dir=${SP_DIR}/ants/tests
    - $PYTHON -m pytest -vs $test_dir -W default --ignore-glob "$test_dir/**/test_integration.py"

about:
  home: https://code.metoffice.gov.uk/doc/ancil/ants/latest/index.html
  license: BSD
  license_family: BSD
  summary: ANTS is a versatile Python library for developing ancillary applications.