{% set name = "ants" %}
{% set version = os.environ.get('VERSION') %}

package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  svn_url: https://code.metoffice.gov.uk/svn/ancil/ants/tags/{{ version }}
  svn_rev: {{ environ["REVISION"] }}
  svn_username: {{ environ["SVN_USERNAME"] }}
  svn_password: {{ environ["SVN_PASSWORD"] }}

build:
  number: 0
  skip: true # [not linux64]

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - numpy<2
    - cartopy
    - dask
    - esmpy
    - f90nml
    - gdal
    - mule-base
    - mule-utils
    - numba
    - pykdtree
    - python-stratify
    - shumlib
    - scitools-iris
    - um-spiral-search

test:
  requires:
    - pytest
  imports:
    - ants
  commands:
    - ancil_2anc.py -h
    - ancil_create_shapefile.py -h
    - ancil_fill_n_merge.py -h
    - ancil_general_regrid.py -h
    - ants-version
    # ANTS test suite fails for different reasons, but it doesn't necessarily mean
    # the actual package is not usable. For now we cannot run the tests.
    # - $PYTHON -m unittest discover -vs ${SP_DIR}/ants/tests

about:
  home: https://code.metoffice.gov.uk/doc/ancil/ants/latest/index.html
  license: BSD
  license_family: BSD
  summary: ANTS is a versatile Python library for developing ancillary applications.