{% set name = "mule" %}
# {% set version = environ.get("VERSION") %}
# {% set revision = environ.get("REVISION") %}
{% set version = '1.0' %}
{% set revision = '126922' %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  svn_url: https://code.metoffice.gov.uk/svn/um/mule/trunk
  svn_rev: {{ revision }}
  svn_username: {{ environ["SVN_USERNAME"] }}
  svn_password: {{ environ["SVN_PASSWORD"] }}

build:
  number: 0 # [linux-64] 
  number: 1 # [not linux-64]

requirements:
  build:
    - python
    - {{ compiler('c') }}
  host:
    - python {{ python }}
    - pip
    - numpy <2 # [py<313]
    - numpy >=2 # [py>=313]
    - six
    - pillow
    - setuptools
    - shumlib # [linux-64]
  run:
    - python
    - six
    - pillow
    - shumlib # [linux-64]
    - mo_pack # [not linux-64]
    - {{ pin_subpackage('um-spiral-search', exact=True) }} # [linux-64]
    # - {{ pin_subpackage('um-packing', exact=True) }} # [linux-64]
    # - {{ pin_subpackage('mule-base', exact=True) }}
    # - {{ pin_subpackage('um-ppibm', exact=True) }} # [linux-64]
    # - {{ pin_subpackage('mule-utils', exact=True) }} # [linux-64]

about:
  home: https://github.com/metomi/mule
  license: BSD
  license_family: BSD
  summary: Mule is a Python API for accessing the various file types used by the UM; the UK Met Office's Unified Model.

outputs:
  - name: um-spiral-search
    files:
      - lib/python{{ python }}/site-packages/um_spiral_search
      - lib/python{{ python }}/site-packages/um_spiral_search-{{ version }}.dist-info
    build:
      skip: true # [not linux-64]
    requirements:
      host:
        - python {{ python }}
      run:
        - python
        - shumlib
    test:
      imports:
        - um_spiral_search
      commands:
        - ${PYTHON} -m unittest discover -vs ${SRC_DIR}/um_spiral_search/lib/um_spiral_search/tests

  # - name: um-packing
  #   files:
  #     - lib/python{{ python }}/site-packages/um_packing
  #     - lib/python{{ python }}/site-packages/um_packing-{{ version }}.dist-info
  #   build:
  #     skip: true # [not linux-64]
  #   requirements:
  #     host:
  #       - python
  #     run:
  #       - python
  #       - six
  #       - shumlib
  #   test:
  #     imports:
  #       - um_packing
  #     commands:
  #       - ${PYTHON} -m unittest discover -vs ${SRC_DIR}/um_packing/lib/um_packing/tests

  # - name: mule-base
  #   files:
  #     - lib/python{{ python }}/site-packages/mule
  #     - lib/python{{ python }}/site-packages/mule-{{ version }}.dist-info
  #   build:
  #     number: 0 # [linux-64] 
  #     number: 1 # [not linux-64]
  #   requirements:
  #     host:
  #       - python
  #     run:
  #       - python
  #       - six
  #       - {{ pin_subpackage('um-packing', exact=True) }} # [linux-64]
  #       - mo_pack # [not linux-64]
  #   test:
  #     requires:
  #       - {{ pin_subpackage('um-packing', exact=True) }}  # [linux-64]
  #     imports:
  #       - mule
  #     commands:
  #       - ${PYTHON} -m unittest discover -vs ${SRC_DIR}/mule/lib/mule/tests

  # - name: um-ppibm
  #   files:
  #     - lib/python{{ python }}/site-packages/um_ppibm
  #     - lib/python{{ python }}/site-packages/um_ppibm-{{ version }}.dist-info
  #   build:
  #     skip: true # [not linux-64]
  #   requirements:
  #     host:
  #       - python
  #     run:
  #       - python
  #       - six
  #       - shumlib
  #       - {{ pin_subpackage('mule-base', exact=True) }}
  #   test:
  #     requires:
  #       - {{ pin_subpackage('mule-base', exact=True) }}
  #     imports:
  #       - um_ppibm

  # - name: mule-utils
  #   files:
  #     - bin
  #     - lib/python{{ python }}/site-packages/um_utils
  #     - lib/python{{ python }}/site-packages/um_utils-{{ version }}.dist-info
  #   build:
  #     skip: true # [not linux-64]
  #   requirements:
  #     host:
  #       - python
  #     run:
  #       - python
  #       - six
  #       - pillow
  #       - shumlib
  #       - {{ pin_subpackage('mule-base', exact=True) }}
  #       - {{ pin_subpackage('um-ppibm', exact=True) }}
  #   test:
  #     requires:
  #       - {{ pin_subpackage('mule-base', exact=True) }}
  #       - {{ pin_subpackage('um-ppibm', exact=True) }}
  #     imports:
  #       - um_utils
  #     commands:
  #       # Set directory where tests are stored
  #       - TEST_DIR=${SRC_DIR}/um_utils/lib/um_utils/tests
  #       # Rename test to avoid 'select' module name clash
  #       - mv ${TEST_DIR}/select ${TEST_DIR}/mule_select
  #       - ${PYTHON} -m unittest discover -vs ${TEST_DIR}
  #       - mule-convpp -h
  #       - mule-cumf -h
  #       - mule-cutout -h
  #       - mule-editmask -h
  #       - mule-fixframe -h
  #       - mule-pumf -h
  #       - mule-select -h
  #       - mule-summary -h
  #       - mule-trim -h
  #       - mule-unpack -h
  #       - mule-version -h