{% set version = environ.get("VERSION") %}

package:
  name: mule
  version: '{{ version }}'

source:
  svn_url: https://code.metoffice.gov.uk/svn/um/mule/trunk
  svn_rev: {{ environ["REVISION"] }}
  svn_username: {{ environ["SVN_USERNAME"] }}
  svn_password: {{ environ["SVN_PASSWORD"] }}

build:
  number: 0

requirements:
  host:
    - python
    # - numpy <2 # [py<313]
    # - numpy >=2 # [py>=313]
    - pip
    - setuptools
  run:
    - python
    - numpy
    - six
    - um_packing =={{version}} # [linux]
    - mo_pack # [not linux]

test:
  imports:
    - mule

about:
  home: https://code.metoffice.gov.uk/trac/um/wiki/working_practices_mule
  license: BSD
  license_file: mule/LICENCE.txt
  summary: Unified Model Fields File interface