name: Release package
on:
    workflow_dispatch:
        inputs:
            package_name:
                description: 'Name of the package to release'
                type: string
                required: true
            version:
                description: 'Version of the package to release'
                type: string
                required: true
            revision:
                description: 'SVN revision associated with the package version to release'
                type: string
                required: true
run-name: Release ${{ inputs.package_name }} ${{ inputs.version }}

jobs:
    release-conda-package:
        name: Build with conda and release
        runs-on: ubuntu-latest
        env:
            BUILD_FOLDER: ${{github.workspace}}/build
            TAG_NAME: ${{inputs.package_name}}-${{inputs.version}}
            VERSION: ${{inputs.version}} # Needed as an env variable for the conda recipe
            REVISION: ${{inputs.revision}} # Needed as an env variable for the conda recipe
            SVN_USERNAME: ${{secrets.MOSRS_USERNAME}} # Needed as an env variable for the conda recipe
            SVN_PASSWORD: ${{secrets.MOSRS_PASSWORD}} # Needed as an env variable for the conda recipe
        permissions:
            contents: write
        steps:
          - name: Checkout source
            uses: actions/checkout@v4
            with:
                fetch-depth: 0 
        
          - name: Create tag
            shell: bash -el {0}
            run: |
                # Create tag in the format <package_name>-<version>
                git tag ${{env.TAG_NAME}}
                git push origin tag ${{env.TAG_NAME}}

          - name: Setup conda build environment
            uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca # v3.0.4
            with:
                miniconda-version: "latest"
                python-version: ${{ vars.PY_VERSION }}
                environment-file: env-build.yml
                auto-activate-base: false
                auto-update-conda: false
                show-channel-urls: true
      
          - name: Build conda package
            shell: bash -el {0}
            run: |
                conda build packages/${{inputs.package_name}} --no-anaconda-upload --output-folder=${{env.BUILD_FOLDER}}
        
          - name: Get package path
            shell: bash -el {0}
            run: |
                path=$(find ${{env.BUILD_FOLDER}} -type f -name *.tar.bz2)
                echo "PACKAGE_PATH=$path" >> $GITHUB_ENV

        #   - name: Upload conda package to Anaconda.org
        #     shell: bash -el {0}
        #     run: |
        #         anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --user ${{ secrets.ANACONDA_USER_NAME }} ${{env.PACKAGE_PATH}}        

          - name: Create Release
            uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 #v2.0.8
            with:
                tag_name: ${{env.TAG_NAME}}
                name: ${{inputs.package_name}} ${{env.VERSION}}
                generate_release_notes: false
                fail_on_unmatched_files: true
                files: |
                    ${{env.PACKAGE_PATH}}

