name: Release package
on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Name of the package to release'
        type: string
        required: true
      revision:
        description: 'SVN revision associated with the package version to release'
        type: string
        required: true
run-name: "Release ${{ inputs.package_name }}"

jobs:
  create-conda-package:
    name: Create conda package
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.create-tag.outputs.tag_name }}
    env:
      REVISION: ${{ inputs.revision }} # Needed as an env variable for the conda recipe
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Cache SVN auth for MOSRS
        uses: access-nri/actions/.github/actions/cache-svn-auth@main
        with: 
          username: '${{ secrets.MOSRS_USERNAME }}'
          password: '${{ secrets.MOSRS_PASSWORD }}'
          realm: '<https://code.metoffice.gov.uk:443> Met Office Code'
    
      - name: Get package version
        id: get-version
        run: |
          # Extract the version from svn property `fcm:revision`
          VERSION=$(bash packages/${{ inputs.package_name }}/get-version.sh ${{ env.REVISION }})
          echo "${{ inputs.package_name }} version: $VERSION"
          # Add VERSION to the environment variables as it's needed by the conda recipe
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        
      - name: Create tag
        id: create-tag
        run: |
          # Create tag in the format <package_name>-<version>
          TAG_NAME="${{ inputs.package_name }}-${{ env.VERSION }}"
          git tag $TAG_NAME
          git push origin tag $TAG_NAME
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUTS
      
      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@b09ef9b599704322748535812ca03efb2625677b #v2.0.5
        with:
          environment-file: env-build.ym

      - name: Build and upload conda package
        id: build-upload
        uses: ACCESS-NRI/action-build-and-upload-conda-packages@davide/7-enable-multi-outputs
        with:
          meta_yaml_dir: packages/${{ inputs.package_name }}/recipe
          user: ${{ secrets.ANACONDA_USERNAME }}
          token: ${{ secrets.ANACONDA_TOKEN }}
          conda_build_args: -c atteggiani -c accessnri -c conda-forge -c nodefaults
          
      - name: Create Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 #v2.3.2
        with:
          tag_name: ${{ steps.create-tag.outputs.tag_name }}
          name: ${{ inputs.package_name }} ${{ env.VERSION }}
          generate_release_notes: false
          fail_on_unmatched_files: true
          files: |-
            ${{steps.build-upload.outputs.paths}}

  cleanup-tag-on-failure:
    name: Cleanup tag
    runs-on: ubuntu-latest
    needs: create-conda-package
    # Run this job if any of the previous jobs failed (and don't skip if any of the needed jobs is skipped)
    if: ${{ ( always() && failure() ) || cancelled() }}
    permissions:
      contents: write
    env:
      TAG_NAME: ${{ needs.create-conda-package.outputs.tag_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: true
  
      - name: Delete tag
        run: |
          if git rev-parse '${{ env.TAG_NAME }}' &>/dev/null; then
              git push origin :${{ env.TAG_NAME }}
              echo "A job in the current workflow failed. Tag '${{ env.TAG_NAME }}' was deleted."
          fi