name: Test Cache SVN Auth Action
on:
  push:

jobs:
  test-action:
    name: Test Cache SVN Auth Action
    runs-on: ubuntu-latest
    steps:
      - name: Run action
        id: run-action
        uses: access-nri/actions/.github/actions/cache-svn-auth@3416c8262beac914e556b7025cf369ccd16e328e
        with: 
          username: '${{ secrets.MOSRS_USERNAME }}'
          password: '${{ secrets.MOSRS_PASSWORD }}'
          realm: '<https://code.metoffice.gov.uk:443> Met Office Code'
    
      - name: Try authenticating
        run: |
          svn info --non-interactive https://code.metoffice.gov.uk/svn/utils/shumlib/trunk/